plugins {
    id 'fabric-loom' version '1.6-SNAPSHOT'
    id 'java'
}

group = 'com.arenix.client'
version = '1.0.0'

repositories {
    mavenCentral()
    maven {
        name "Fabric"
        url "https://maven.fabricmc.net/"
    }
}

dependencies {
    // Fabric
    minecraft "com.mojang:minecraft:1.21.4"
    mappings "$project.group:yarn:$minecraft_version+build.mapping:release"
    modImplementation "net.fabricmc:fabric-loader:$fabric_loader_version"

    // Fabric API
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"

    // Mixin
    modImplementation "net.fabricmc:fabric-api:${project.fabric_api_version}" // For mixin support
}

// Task to run the game
loom {
    accessWidenerPath = file("src/main/resources/arenixclient.accesswidener") // Specify access widener file
}

java {
    withJavadoc()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
}

tasks.register('clean', Delete) {
    delete rootProject.buildDir
}
