# Project properties for Minecraft Fabric mod development.

# Specifies the Minecraft version.
minecraft_version=1.21.4

# Specifies the Fabric Loader version.
fabric_loader_version=0.15.11

# Specifies the Fabric API version.
fabric_api_version=0.100.0+1.21.4

# Specifies the Java version to be used.
java_version=17

# The mod ID, which uniquely identifies your mod.
mod_id=arenix
