# Project properties
project.group = com.arenix.client
project.version = 1.0.0

# Minecraft version
minecraft_version = 1.21.4

# Fabric Loom version
fabric_loom_version = 1.6-SNAPSHOT

# Fabric Loader version
fabric_loader_version = 0.15.11

# Fabric API version
# Check for the latest compatible version on https://www.curseforge.com/minecraft/mc-mods/fabric-api/files/all
fabric_api_version = 0.100.3+1.21.4

# Development environment
net.fabricmc.fabricdev.developer.minecraft_home = ${user.home}/.gradle/caches/fabric-loom/minecraft
net.fabricmc.fabricdev.developer.java_home = ${java.home}

# Gradle properties
org.gradle.parallel = true
org.gradle.caching = true
